# -*- coding: utf-8 -*-
"""yolov10-crowd-counting-project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sbkhgr_2cNpdc-UR4coHug95J5_NS_Yu
"""

!pip install roboflow
!pip install ultralytics

# Import required libraries
from ultralytics import YOLO
from roboflow import Roboflow
import cv2
import matplotlib.pyplot as plt
import torch

# Check if GPU is available (optional but recommended)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Using device: {device}')

rf = Roboflow(api_key="Wxv8xhhcQ6dFDODLgXpR")
project = rf.workspace("crowd-dataset").project("crowd-counting-dataset-w3o7w")
version = project.version(2)
dataset = version.download("yolov8")

model = YOLO("yolov10n.pt")
#train model
model.train(data="/content/crowd-counting-dataset-2/data.yaml", epochs=30, imgsz=640, batch=2, device=device)

# Import required libraries
import cv2
from matplotlib import pyplot as plt
from google.colab import files
from ultralytics import YOLO

# Load your custom trained model
model = YOLO("runs/detect/train2/weights/best.pt")

# Upload an image for testing
uploaded = files.upload()

# Read and display the uploaded image
image_path = list(uploaded.keys())[0]
img = cv2.imread(image_path)

# Run inference on the uploaded image
results = model(image_path)

# Display results using OpenCV (Bounding boxes)
for result in results:
    # Extract bounding boxes and labels
    annotated_img = result.plot()  # Draws boxes and labels onto the image

    # Use matplotlib to display the annotated image
    plt.imshow(cv2.cvtColor(annotated_img, cv2.COLOR_BGR2RGB))
    plt.axis('off')  # Hide axis
    plt.show()

# Count people in the crowd (each detection is considered one person)
people_count = len([box for box in results[0].boxes if box.cls == 0])  # Assuming '0' is the class for 'person'
print(f"Number of people detected: {people_count}")